name=input('\nName: ')
address=input('Address: ')
phone=int(input('Phone number: '))
mail_id=input('Mail id:')
c=input('\nUG - Name of College,Percentage : ')
d=input('10 - Name of School, Percentage : ')
e=input('12 - Name of School, Percentage : ')
print('\n')
print("PERSONAL DETAIL:")
print('____________________________________________________')
print('\nName: ',name)
print('Address: ',address)
print('Phone number: ',phone)
print('Mail id:',mail_id)
print('\n')
print('EDUCATION')
print('____________________________________________________')
print(c)
print(d)
print(e)
